### ISSUE TITLE
Ip adress of sp108e

### ISSUE THREAD

**Issue by savage008** [kylezimmerman/pyledshop#1]
Hi,

I would like to use this script to integrate  in to my domoticz setup, where do i  put the ip adres of the sp108e?

Grtz, edwin.

**Comment by kylezimmerman** [comment]
Hi @savage008,

You would need to provide the IP address to the `WifiLedShopLight` constructor. I'm not familiar with domoticz (I made this library for a custom homeassistant component) but it should still work for you.

For example, if your sp108e has an IP of 192.168.0.103 then you'd do the following:

```py
from pyledshop import WifiLedShopLight
light = WifiLedShopLight("192.168.0.103")
```

Let me know if you get it working or if you need any more info.

**Comment by redviper2100** [comment]
Nice tip. But could you give me an example for running a specific effect, brightness or speed?

I appreciate your time to decode this chinese controller! Great Job!

**Comment by redviper2100** [comment]
I figured it out.

```
from pyledshop import WifiLedShopLight
light = WifiLedShopLight("192.0.1.164")
light.set_speed(100)
```

**Comment by kylezimmerman** [comment]
Updated the docs to include example usage
