### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Ace0510** [kylezimmerman/pyledshop#3]
Hi Kyle, I downloaded the folder & files, but I am not sure where to put them in. For now I place them in \\HA_IP\config\custom_components, but I do not know what to do next. Also I am not sure how to use the yaml code. Should be placed in the configuration file? Some place else? Any guidance will be great. 
Thanks!

**Comment by gibbiemonster** [comment]
@Ace0510 - This is not a Home Assistant component. I'm trying to make one, however, this is only a Python module to control the controller with code.
